# Generated by Django 3.0.1 on 2020-01-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_auto_20200104_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
            preserve_default=False,
        ),
    ]
