# Generated by Django 3.0.1 on 2020-01-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='test-product', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('White', 'White')], max_length=6),
        ),
    ]
