# Generated by Django 3.0.1 on 2020-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0011_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('minimum_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
